type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Minister of Education award"
subtitle = "Organization"
date = "2021"
content = "1. Minister of Education award at ‘2021 Excellent Participant of the BK21 Project Phase 4’. Sangheon Jeon received the award in recognition of outstanding results. Feb. 2021."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2024"
content = "Description of the award."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2023"
content = "Description of the award."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2022"
content = "Description of the award."
